# NumPy Exercise (5 points)

The homework assignment is due by the end of the day on Thursday, October 3.

You are expected to solve the assignment problems independently and adhere to the university's policies for academic honesty and integrity. Copying solutions to the assignment problems from your classmates, the internet, or anywhere else is strictly prohibited.

To avoid potential conflicts between variable names in your notebook, it is recommended to restart the kernel often or for every new problem by selecting `Kernel -> Restart Kernel...`. Also, when you complete all problems and before submitting the notebook, ensure that all cells have been executed without errors by selecting `Kernel -> Restart Kernel and Run All Cells...`.

**Note that your solutions are expected to follow the code examples provided in the lecture notes. If your solution to a problem uses functions or codes that are not covered in the lecture notes, that will result in zero marks assigned for that problem.**

NumPy exercise: 5 points

Total points for Assignment 3: 25 points

## Part 1. Array Construction (2 points)

(1.1) Create a 2x10 array (two rows and ten columns) named `ary1`, consisting of all zeros and using integer numbers as the data type. 

In [23]:
# Your code here

import numpy as np

ary1 = np.zeros((2, 10))
print("ary1:\n", ary1)

ary1:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


(1.2) Create an array named `ary2` consisting of 10 ones using float numbers as the data type. Next, create an array named `ary3` consisting of 10 threes using integer numbers. Afterward, concatenate the three arrays (ary1, ary2, ary3) horizontally to obtain a 4x10 array named `ary4`.

In [26]:
# Your code here

ary2 = np.ones(10, dtype = float)
print("ary2:\n", ary2)
print()

ary3 = np.ones(10, dtype = int)
ary3 = ary3 * 3
print("ary3:\n", ary3)
print()

ary4 = np.concatenate((ary1.reshape(-1), ary2, ary3))
print("ary4:\n", ary4)
print(ary4.shape)
print()


ary2:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

ary3:
 [3 3 3 3 3 3 3 3 3 3]

ary4:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
(40,)



(1.3) Display the data type of `ary4`. Why it is that data type? What can you conclude about concatenating integers and floats in NumPy?

In [ ]:
# Your code here



(1.4) Create a numpy array of integers from 10 to 50 using `arange`.

In [8]:
# Your code here

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

(1.5) Create a numpy array of the "even" integers from 5 to 29.

In [9]:
# Your code here

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

(1.6) Create a 3x4 array with values ranging from 0 to 12, using `arange` and `reshape`.

In [10]:
# Your code here

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Part 2. Random Number Generators (1 point)

(2.1) Generate an array called `ary5` having 30 random numbers sampled from a normal distribution with mean=15 and standard deviation=2, by applying a Random State to the random number generator. 

In [11]:
# Your code here
# Obviously, since these are random numbers your solution will be different than those shown below

array([12.82873879, 16.99469089, 15.565957  , 11.98741057, 13.8427995 ,
       18.30287307, 10.14664151, 14.14217474, 17.53187252, 13.2665192 ,
       13.6422277 , 14.81058206, 17.98277925, 13.72219601, 14.11203608,
       14.13129745, 19.41186017, 19.37357218, 17.0081078 , 15.7723728 ,
       16.47473715, 17.98146406, 13.12833226, 17.35165809, 12.49223866,
       13.724497  , 16.81421039, 12.1426386 , 14.71986256, 13.27649021])

(2.2) Display the indices of the elements in `ary5` sorted in ascending order. 

In [12]:
# Your code here

array([ 6,  3, 27, 24,  0, 22,  9, 29, 10, 13, 25,  4, 14, 15,  7, 28, 11,
        2, 19, 20, 26,  1, 18, 23,  8, 21, 12,  5, 17, 16], dtype=int64)

(2.3) Generate a 4x5 array called `ary6` of random numbers sampled from a uniform distribution. Use the random seed `12` to ensure reproducibility. 

In [13]:
# Your code here

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496],
       [0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741, 0.76813415, 0.16071675]])

(2.4) Display the average values of the rows of `ary6`.

In [14]:
# Your code here

array([0.34116838, 0.58940839, 0.53782629, 0.4974984 ])

(2.5) Display the index of the minimum element in each column in `ary6`. 

In [15]:
# Your code here

array([0, 3, 1, 0, 2], dtype=int64)

## Part 3. Boolean Masks for Indexing (0.5 points)

(3.1) Create a Boolean mask of the elements in `ary6` that are in the range between 0.3 and 0.8, and afterward use the mask to extract the elements into a new array `ary7`.

In [18]:
# Your code here

array([0.7400497 , 0.53373939, 0.60608318, 0.52122603, 0.55203763,
       0.48537741, 0.76813415])

## Part 4. Reshaping NumPy Arrays (1.5 points)

(4.1) Flatten `ary6` using both `flatten()` and `ravel()` and check if the resulting arrays are views of `ary6` (i.e., whether they share the same memory).

In [ ]:
# Your code here

(4.2) Create an array of 40 linearly spaced data points between 3 and 5.

In [23]:
# Your code here

array([3.        , 3.05128205, 3.1025641 , 3.15384615, 3.20512821,
       3.25641026, 3.30769231, 3.35897436, 3.41025641, 3.46153846,
       3.51282051, 3.56410256, 3.61538462, 3.66666667, 3.71794872,
       3.76923077, 3.82051282, 3.87179487, 3.92307692, 3.97435897,
       4.02564103, 4.07692308, 4.12820513, 4.17948718, 4.23076923,
       4.28205128, 4.33333333, 4.38461538, 4.43589744, 4.48717949,
       4.53846154, 4.58974359, 4.64102564, 4.69230769, 4.74358974,
       4.79487179, 4.84615385, 4.8974359 , 4.94871795, 5.        ])

(4.3) For the given array `mat`, in the following cells apply slicing operations to replicate the displayed outputs.

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
# Your code here

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
# Your code here

array([[ 2],
       [ 7],
       [12]])

In [27]:
# Your code here

array([[ 8, 10],
       [13, 15]])

In [28]:
# Your code here

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])