# Numpy

- Numpy (short for Numerical Python) is a popular open-source library for numerical computing in Python. It provides a fast and efficient way to work with arrays, matrices, and other numerical data structures.


- Numpy is widely used in __scientific computing, data analysis, and machine learning__ because it offers several benefits over built-in Python data structures like lists. For example, Numpy arrays are __homogeneous__ (i.e., all elements have the same data type) and contiguous in memory, which allows for efficient __vectorized__ operations and faster processing.


- Numpy provides a wide range of functionalities for manipulating arrays, such as element-wise operations, matrix operations, reshaping, slicing, and indexing. Additionally, it supports a variety of numerical data types, including integers, floating-point numbers, and complex numbers.


- Numpy also integrates well with other scientific computing libraries in Python, such as SciPy (for scientific computing) and Matplotlib (for data visualization).

## Numpy array

NumPy’s main object is the __homogeneous multidimensional__ array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. 

NumPy’s array class is called `ndarray` (or `array` for short). 

In NumPy dimensions of an array are called __axes__.

In [1]:
#create a one dimensional array
import numpy as np
a= np.array([1,5,7])
print(a.shape)

(3,)


This array has one axis. That axis has 3 elements in it, so we say it has a length of 3.

In [2]:
# create a two dimensional array
A= np.array([[3,5,7],[10,4,5]])
print(A.dtype)


int64


This array has two axes. The first axis has a length of 2, the second axis has a length of 3.

## Some basic properties:

- __ndarray.ndim:__ the number of axes (dimensions) of the array.


- __ndarray.shape:__ the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

- __ndarray.size:__ the total number of elements of the array. This is equal to the product of the elements of shape.

- __ndarray.dtype:__ an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

- __ndarray.itemsize:__ the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.


In [3]:
# Basic properties 

The type of the array can also be explicitly specified at creation time:

In [4]:
#imposing the data type at creation

## Quick creation: zeros, ones, empty

- The function __zeros__ creates an array full of zeros, 

- The function __ones__ creates an array full of ones, 

- The function __empty__ creates an array whose initial content is random and depends on the state of the memory. 

By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [5]:
# Quick creation: zeros, ones, empty
empty = np.empty([10,5])
empty

array([[3.10503618e+231, 2.32035006e+077, 1.23516411e-322,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        2.14624923e-314, 6.93053804e-310],
       [0.00000000e+000, 0.00000000e+000, 6.93053812e-310,
        2.14624923e-314, 2.14624923e-314],
       [2.14624923e-314, 2.14624923e-314, 6.93053807e-310,
        6.93052455e-310, 2.14624923e-314],
       [6.93053807e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.14624923e-314, 6.93053773e-310,
        6.93053806e-310, 6.93053773e-310],
       [6.93053773e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000

## Quick creation: arrange

- To create sequences of numbers, NumPy provides the __arange__ function which is analogous to the Python built-in __range__, but returns an array.

In [6]:
# arange

## Quick creation: linspace

- When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function __linspace__ that receives as an argument the number of elements that we want, instead of the step:

In [7]:
#linspace 

## Basic Operations: elementwise

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [8]:
# Elementwise multiplication

In [9]:
# Addition, subtraction

In [10]:
# Scalar multiplication

In [11]:
# Comparision 

In [12]:
# Selection/filtering

In [13]:
#Summing & stats

In [14]:
# Advanced function: trig, exp, etc

__Practice problem 1:__ Compute the sum $\sum_{n=1}^{100} \sin(n).$

__Practice problem 2:__ Plot the function $y=x^2$ on the interval $[-1,1]$. 

## Basic Operations: matrix multiplication

Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator (in python >=3.5) or the `dot` __function__ or __method__

In [2]:
import numpy as np
A = np.array([[3,4,1],[0,1,1]])
B = np.array([[2,1],[1,0]])
print(A)
print(B)

[[3 4 1]
 [0 1 1]]
[[2 1]
 [1 0]]


In [8]:
B@A

array([[6, 9, 3],
       [3, 4, 1]])

In [9]:
B.dot(A)

array([[6, 9, 3],
       [3, 4, 1]])

In [10]:
np.dot(B,A)

array([[6, 9, 3],
       [3, 4, 1]])

Adding a new axis into the numpy array

In [13]:
a = np.array([3,2,1])
a = a[:,np.newaxis]
a.shape

(3, 1)

In [19]:
b = np.array([1.4,1])
b = b[np.newaxis,:]
b.shape

(1, 2)

In [20]:
a@b

array([[4.2, 3. ],
       [2.8, 2. ],
       [1.4, 1. ]])

## Check out ticket

__Problem:__ Compute the sum $\sum_{m=1}^{50} \sum_{n=1}^{100} \sin(mn).$

In [23]:
oursum = 0
for m in range(1,51):
    for n in range(1,101):
        oursum += np.sin(m*n)
print(oursum)

67.14305583771502


In [30]:
m = np.arange(1,51)
m = m[:,np.newaxis]
n = np.arange(1,101)
n = n[np.newaxis,:]
mn = m@n
mn
new_sum = np.sum(np.sin(mn))
print(new_sum)

67.14305583771494
