## Homework 3: Implement NN from Scratch

In [78]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

#### Load the dataset

In [79]:
df=pd.read_csv('winequality-white.csv', sep = ';')
X = df.values[:, :11]
Y = df.values[:, 11]
print('Data shape:', 'X:', X.shape, 'Y:', Y.shape)

# data normalization
min_vals = np.min(X, axis = 0)
max_vals = np.max(X, axis = 0)
X = (X-min_vals)/(max_vals-min_vals) 

# train set and test set preparation
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)
y_train =  np.expand_dims(y_train, axis=1)
y_test =  np.expand_dims(y_test, axis=1)
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

Data shape: X: (4898, 11) Y: (4898,)
(3428, 11) (1470, 11)
(3428, 1) (1470, 1)


#### Task 1: Activation functions. 5 points

1.1 Implement the ReLU function. 

In [62]:
def sigm(z):
    return 1/(1 + np.exp(-z))

def dsigm(z):
    return sigm(z)*(1 - sigm(z))

def softmax(z):
    '''   
        parameter: z: m_batch * n_features
        return: m_batch * n_features
            
    '''
    b = np.exp(z - np.max(z, axis = 1, keepdims = True))# np.max(z)
    return b / np.sum(b, axis = 1, keepdims = True)


def ReLU(z):
    ''' The ReLU function
    
        parameter:
            z: m_batch * n_features
        return: m_batch * n_features
            
    '''
    #-----add your code here----

    
    #-------------------------
    
z = np.array([[-1, 2, -3], [4, -2, 4]])
print('softmax output:\n', softmax(z))
print('ReLU output:\n', ReLU(z))

softmax output:
 [[0.04712342 0.94649912 0.00637746]
 [0.49938108 0.00123784 0.49938108]]
ReLU output:
 [[0 2 0]
 [4 0 4]]


#### Task 2: Create the lalyer class. 25 points

    2.1 Implement the Xavier initialization to initilize W and bias. 10 points
    2.2 Complete the run function. 5 points
    2.3 Create layers and process data samples. 10 poits

In [60]:
class Layer:
   
    def __init__(self, units, input_dim, activation = None): 
        #Student can use any method. But cannot initialize W and bias as zeros.

        self.units = units
        self.activation = activation
        self.input_dim = input_dim
        
        np.random.seed(0)
        
        # 2.1 Implement the Xavier initialization to initilize W and bias 
        #check here: https://www.deeplearning.ai/ai-notes/initialization/
        ## add you code here-------------
 


        ##----------------------
        
        self.gW = np.zeros((units, input_dim))
        self.gb = np.zeros((units,1))
        
    def run(self, inputs):
        ''' calculate the net input and activation output of the current layer
        
            inputs=(n_sample * n_features)
          
            return the activation output
        '''
        #calculate the net input
        
        self.net = np.dot(inputs, self.W.T) + self.bias.T
       
        #2.2 activation output 
        ## add you code here--------

        
        
        ##------------------------------     
        return self.output

In [9]:
## 2.3 create a liner and non-linear layers with 2 nodes/units, input the first two training samples, and print the output

#add your code here----------------------
# create a linear layer with 2 nodes/units and print out for processing the first two samples



# create a non-linear layers with 2 nodes/units and the sigmoid activation and print out for processing the first two samples


#----------------------------------

weights: [[ 0.53188179  0.12065194  0.29510061  0.67565472  0.56308992 -0.29466037
   0.28646244 -0.04563592 -0.03112165  0.12380011  0.04343077]] Bias: [[1.45427351]]
Output: [[2.09251453]
 [1.94740246]]
weights: [[ 0.53188179  0.12065194  0.29510061  0.67565472  0.56308992 -0.29466037
   0.28646244 -0.04563592 -0.03112165  0.12380011  0.04343077]] Bias: [[1.45427351]]
Output: [[0.8901735 ]
 [0.87516313]]


#### Task 3: Create NN. 50 points

    3.1 Implement the loss function. 5 points
    3.2 Complete the following 'train' function. 10 points
    3.3 Implement the BP algorithm. CS 474 students will earn 10 extra points for processing more than three layers. It is required for CS574 students to implement BP for processing more than 3 layers. 30 points
    3.4 update all weights and bias. 5 points 

In [63]:
class NeuralNetwork:
    
    def __init__(self):
        self.layers=[] #list of layers
        
    def add(self, units, input_dim, activation = None):
        '''add layers to NN
            
            units: the number of nodes
            input_dims: input dimensions
            activation: activation fundtions
        
        '''
        layer = Layer(units, input_dim, activation)
        self.layers.append(layer)
    
    def forward_prop(self, inputs):
        '''forward propagation calculates net input and output for each layer
        
            inputs: input data(n_samples * n_features)
            return the output of the last layer: n_samples * n_output_nodes
            
        '''
        
        nLayers = len(self.layers)
        #print(nLayers)
        for i in range(nLayers):
            out = self.layers[i].run(inputs)
            inputs = out   
        return out
    
    # 3.1 implement the loss function. 5 points
    def loss(self, y_pred, y):
        '''loss function: 1/(2*n_samples)*sum_samples((y_i-y_pred_i)**2)
            y_pred: predictions(n_samples * 1)
            y: target(n_samples * 1)
        '''
        #add your code here-------------------

        
        #------------------------------------
    
    # implement the prediction function.
    def predict(self, x):
        '''predict
            x: input(n_samples * n_features) 
            return predicted values
        '''
        out = self.forward_prop(x)
        return out
         

    #3.2 complete the following 'train' function. 10 points
    def train(self, inputs, targets, lr = 0.001, batch_size = 32, epochs = 50):
        '''implement the SGD process and use Back-Propagation algorithm to calculate gradients 
        
            inputs: training samples
            targets: training targets
            lr: learning rate
            batch_size: batch size
            epochs: max number of epochs
        '''
        
        m = len(targets)  
        loss_hist = np.zeros(epochs)
        
        for i in range(epochs):
            #shuffle the data
            idx = np.arange(m)
            np.random.shuffle(idx)
            inputs = inputs[idx]
            targets = targets[idx]
            
            for b in range(int(m/batch_size)):
                b_start= b*batch_size
                b_end = min((b+1)*batch_size, m)
                
                x_batch = inputs[b_start:b_end, :]
                y_batch = targets[b_start:b_end, :]
                #print(x_batch.shape)
                
                #add your code here------------------------------
                # 1)run forward propagation to get output of the current mini-batch

                
                # 2)call BP to calculate all gradients

                
                # 3)update all weights and bias

                #-------------------------------------------------
                
            lr = lr*0.99  
            #add your code here---------------------------
            # 4) calculate and record the loss of current epoch

            # 5) print out the loss of current epoch

            #-----------------------------------------
        return loss_hist
   
    #3.3 implement the BP algorithm. 30 points
    def BP(self, x, y):
        ''' Back-propagation algorithm
        
            x: input samples (n_samples * n_features)
            y: predicted values
        '''
        
        nLayers = len(self.layers)
        m_batch = x.shape[0]
        
        #add your code here------------------------------------
        # CS474 students are required to perform BP for three layers
        # CS 574 students are required to perform BP for more than three layers


        #------------------------------------------------------------
        
    #3.4 update all weights and bias. 5 points         
    def updateWeights(self, lr):
        nLayers = len(self.layers)
        #add your code here------------------------------------------------------

        #------------------------------------------------------------------------       

#### Task 4: Evaluation. 20 points

    4.1 Create a three-layer NN: The hidden layer has 10 units with sigmoid activation, and the output layer has one unit with None activation.
    4.2 Train the network by calling the train function using the training set: lr = 0.001, batch_size = 8, epochs = 50
    4.3 Plot the loss_hist from the training results
    4.4 Evaluate the trained nn by calcualating the MSE and MAE using using both the training and test sets

##### 4.1 and 4.2 create and train the nn. 5 points

In [77]:
#add your code here--

#------------------

##### 4.3 Plot the loss_hist. 5 points

In [ ]:
#add your code here--

#------------------

##### 4.4 Evaluate the trained nn by calcualating the MSE and MAE using using both the training and test sets. 10 points

In [ ]:
#add your code here--

#------------------

#### Task 5(Optional): Students get 10 extra points for getting better test performance using 
    1)different hyperparameters(batch size, lr, and epochs) and/or 
    2)nn design, e.g., different number of hidden nodes, different number of hidden layers, different activation functions

In [76]:
#add your code here--

#------------------