In [2]:
import numpy as np

In [3]:
# Iris data

from sklearn import datasets as ds

iris = ds.load_iris()
display(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = iris.data
Y = iris.target

print(X.shape, Y.shape)
print(Y)

(150, 4) (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
# split data in to training and test

from sklearn.model_selection import train_test_split

#X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2) 
X_train, Y_train, X_test, Y_test = train_test_split(X, Y, test_size = 0.2) 
# Whatever the test size parameter is set to is the percentage of the data that is split into training

print(X_train.shape)
print(X_train,"\n")
print(Y_train.shape)
print(Y_train,"\n")
print(X_test.shape)
print(X_test,"\n")
print(Y_test.shape)
print(Y_test,"\n")

(120, 4)
[[5.6 2.8 4.9 2. ]
 [5.7 2.5 5.  2. ]
 [5.7 2.8 4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [5.  3.3 1.4 0.2]
 [6.1 2.6 5.6 1.4]
 [5.  3.4 1.5 0.2]
 [5.6 2.9 3.6 1.3]
 [4.8 3.1 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [6.  2.9 4.5 1.5]
 [5.9 3.  5.1 1.8]
 [6.7 3.3 5.7 2.1]
 [5.7 3.8 1.7 0.3]
 [5.9 3.  4.2 1.5]
 [6.3 2.8 5.1 1.5]
 [6.7 3.3 5.7 2.5]
 [7.4 2.8 6.1 1.9]
 [6.5 3.  5.2 2. ]
 [6.8 3.  5.5 2.1]
 [4.9 2.5 4.5 1.7]
 [4.8 3.4 1.6 0.2]
 [5.4 3.  4.5 1.5]
 [5.3 3.7 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [6.3 3.3 4.7 1.6]
 [5.8 2.7 3.9 1.2]
 [7.6 3.  6.6 2.1]
 [4.6 3.1 1.5 0.2]
 [6.4 2.7 5.3 1.9]
 [6.2 3.4 5.4 2.3]
 [5.1 2.5 3.  1.1]
 [7.2 3.2 6.  1.8]
 [6.1 3.  4.9 1.8]
 [6.3 2.3 4.4 1.3]
 [6.4 3.1 5.5 1.8]
 [4.6 3.2 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [6.2 2.8 4.8 1.8]
 [5.6 2.7 4.2 1.3]
 [6.4 2.8 5.6 2.2]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [5.8 2.7 5.1 1.9]
 [6.4 3.2 5.3 2.3]
 [4.3 3.  1.1 0.1]
 [4.8 3.4 1.9 0.2]
 [5.4 3.4 1.7 0.2]
 [5.1 3.8 1.5 0.3]
 [4.4 3.  1.3 0.2]
 [6.  2.2 5.  1.5]
 [4.4 3.2 1.3 0.2]
 [6

In [10]:
def Euclidean_Distance(x1, x2):
    euclidean_distance = 0
    euclidean_distance = np.sqrt(np.sum((x2-x1)**2))
    return euclidean_distance

In [11]:
def findKNgbs(X_train, X_new, K=5):
    """
        X_train: training set
        X_new: test sample
        K: number of nearest neighbors
        
        return: indicies of the K samples from X_train
    """
    
    # use the Euclidean distance
    
    l = []
    highest_index = -1
    for index, X_train_vector in enumerate(X_train):
        euclidean_distance = Euclidean_Distance(X_train[index], X_new)
        
        # if less than K in list
        
        if len(l) < K:
            l.append((index, euclidean_distance)) # inserting tuples in list
        
        # if list is full at K items in it, replace element with lowest
        
        elif len(l) >= K:    
            
            # This solution here doesn't always replace the highest euclidean distance tuple:
            # Ex: l = [1,3,5,7,9] and euclidean_distance = 2
            # Then l = [2,3,5,7,9] when it should be l = [1,3,5,7,2]
            
            """
            for i, ele in enumerate(l):
                if ele[1] > euclidean_distance:
                    del l[i]
                    l.insert(i, (index, euclidean_distance))
                    break
            """ 
            
            # Another solution that is close to working but doesn't because tuple_in_l_with_max_eclid_dist[0] will go out of bounds if replacing because 
            # it doesn't refer to the index in l of the tuple with the max euclidean distance - need a new solution which returns and uses this index:
            
            """
            tuple_in_l_with_max_eclid_dist = max(l, key=lambda x: x[1]) # pull max value of all the values at index 1 in each of the tuples in list l
            print(tuple_in_l_with_max_eclid_dist)
            if tuple_in_l_with_max_eclid_dist[1] > euclidean_distance:
                del l[tuple_in_l_with_max_eclid_dist[0]]
                l.insert(tuple_in_l_with_max_eclid_dist[0], (index, euclidean_distance))
            """
            
            # Improvement of the last attempt that is a solution
            
            #"""
            index_in_l_of_tuple_with_max_eclid_dist, max_eclid_dist_tuple_in_l = max(enumerate(l), key=lambda x: x[1][1]) # pull max value of all the values at index 1 in each of the tuples in list l as well as the index of the tuple with the max value
            #print(index_in_l_of_tuple_with_max_eclid_dist, max_eclid_dist_tuple_in_l)
            if max_eclid_dist_tuple_in_l[1] > euclidean_distance:
                del l[index_in_l_of_tuple_with_max_eclid_dist]
                l.insert(index_in_l_of_tuple_with_max_eclid_dist, (index, euclidean_distance))
            #"""
            
        #print(l, "\n") # print as they add - can comment out for less output
    return l

In [12]:
list_of_index_eclid_dist = findKNgbs(X_train, Y_train, K = 5)
print("Final list of tuples of indices and Euclidean Distances:\n", list_of_index_eclid_dist)

Final list of tuples of indices and Euclidean Distances:
 [(14, 11.405261943506602), (113, 11.42978564978364), (104, 11.53603051313579), (68, 11.583609109426993), (79, 11.575836902790225)]
